### PR TITLE
Use SVG images in readme

### PR DESCRIPTION
**Pull request by SimenB**
`png` looks pretty bad on retina :cry:

### CODE REVIEW

**Comment by tkellen** [comment]
Thanks! Wanna change the liftoff logo itself too? We have an SVG for that.

**Comment by SimenB** [comment]
@tkellen sure. Didn't know about that one, I just assumed it didn't exist :laughing:

**Comment by SimenB** [comment]
@tkellen Hold off a bit, doesn't seem to work properly

**Comment by SimenB** [comment]
@tkellen Your icon I had to serve from rawgit, as it seems it got the wrong request-header if directly from github.

Nodei.co is weirder. the URL (`https://nodei.co/npm/liftoff.svg`) works fine in the browser, but w/e GitHub does to an svg seems to be broken, and throws 404. See https://github.com/SimenB/js-liftoff/blob/badge/README.md

**Comment by tkellen** [comment]
bummer. Say, @rvagg any idea what's up with that?

**Comment by tkellen** [comment]
thanks @SimenB!

**Pull request merged**
